In [20]:
import numpy as np
from math import floor
n = 5
m = 15

w = [12, 2, 1, 1, 4]
v = [4, 2, 1, 2, 10]

#[0, 1,0, 0, 1]

In [2]:
class DNA:
    def __init__(self):
        self.dvar = np.random.randint(0,2,n)
        self.fitness = 0

    
    def calc_fitness(self):
        self.fitness = np.sum(self.dvar * v)
        total_weight = np.sum(self.dvar * w)
        err = total_weight - m
        if total_weight>m:
            self.fitness = self.fitness - 2*err

    def mutate(self):
        for i in range(n):
            if np.random.rand()<0.25:
                self.dvar[i] = 1 - self.dvar[i]
            

In [3]:
dna = DNA()
print(dna.dvar)
print(dna.fitness)

[0 1 0 0 0]
0


In [4]:
def crossover(dna1, dna2):
    new_dna = DNA()
    mid = np.random.randint(0,n)
    a1 = dna1.dvar[0:mid]
    a2 = dna2.dvar[mid:n]
    new_dna.dvar = np.concatenate([a1, a2], axis=None)
    new_dna.calc_fitness()
    return new_dna

In [5]:
d1 = DNA()
print(d1.dvar)
d2 = DNA()
print(d2.dvar)

[0 0 0 0 1]
[1 1 0 0 1]


In [6]:
d3 = crossover(d1, d2)
print(d3.dvar)
print(d3.fitness)

[0 0 0 0 1]
10


In [7]:
d4 = DNA()
print(d4.dvar)


[1 0 1 1 1]


In [8]:
d4.mutate()
print(d4.dvar)

[1 0 1 0 0]


In [16]:
# initialize first population
pop_size = 20
population = []
for i in range(pop_size):
    population.append(DNA())
    population[i].calc_fitness()
    print(population[i].fitness)

13
11
12
12
12
12
15
11
4
2
7
0
6
6
10
1
7
5
10
12


In [23]:
pool = []
for i in range(pop_size):
    for j in range(floor(pow(population[i].fitness,2)/8)):
        pool.append(i)

print(pool)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 10, 10, 10, 10, 10, 10, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 16, 16, 16, 16, 16, 16, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19]


In [ ]:
num_of_iteration = 100

for it in range(num_of_iteration):
    