In [91]:
import numpy as np

n = 5
m = 15

w = [12, 2, 1, 1, 4]
v = [4, 2, 1, 2, 10]

In [92]:
class DNA:
    def __init__(self):
        self.dvar = np.random.randint(0,2,n)
        self.fitness = 0

    
    def calc_fitness(self):
        self.fitness = np.sum(self.dvar * v)
        total_weight = np.sum(self.dvar * w)
        err = total_weight - m
        if total_weight>m:
            self.fitness = self.fitness - 2*err

    def mutate(self):
        for i in range(n):
            if np.random.rand()<0.25:
                self.dvar[i] = 1 - self.dvar[i]
            

In [93]:
dna = DNA()
print(dna.dvar)
print(dna.fitness)

[0 0 0 0 0]
0


In [94]:
def crossover(dna1, dna2):
    new_dna = DNA()
    mid = np.random.randint(0,n)
    a1 = dna1.dvar[0:mid]
    a2 = dna2.dvar[mid:n]
    new_dna.dvar = np.concatenate([a1, a2], axis=None)
    new_dna.calc_fitness()
    return new_dna

In [95]:
d1 = DNA()
print(d1.dvar)
d2 = DNA()
print(d2.dvar)

[1 0 1 0 0]
[1 1 0 0 0]


In [96]:
d3 = crossover(d1, d2)
print(d3.dvar)
print(d3.fitness)

[1 0 0 0 0]
4


In [97]:
d4 = DNA()
print(d4.dvar)


[1 0 0 1 1]


In [98]:
d4.mutate()
print(d4.dvar)

[0 1 0 1 0]
