In [145]:
import numpy as np
from math import floor, inf
n = 10
m = 15

w = [12, 2, 1, 1, 4, 6, 8, 12, 3, 5]
v = [4, 2, 1, 2, 10, 6, 8,  4, 6, 1]

#[0, 1,0, 0, 1]

In [146]:
class DNA:
    def __init__(self):
        self.dvar = np.random.randint(0,2,n)
        self.fitness = 0

    
    def calc_fitness(self):
        self.fitness = np.sum(self.dvar * v)
        total_weight = np.sum(self.dvar * w)
        err = total_weight - m
        if total_weight>m:
            self.fitness = self.fitness - 2*err

    def mutate(self):
        for i in range(n):
            if np.random.rand()<0.25:
                self.dvar[i] = 1 - self.dvar[i]
            

In [147]:
dna = DNA()
print(dna.dvar)
print(dna.fitness)

[0 0 1 0 1 1 1 1 0 1]
0


In [148]:
def crossover(dna1, dna2):
    new_dna = DNA()
    mid = np.random.randint(0,n)
    a1 = dna1.dvar[0:mid]
    a2 = dna2.dvar[mid:n]
    new_dna.dvar = np.concatenate([a1, a2], axis=None)
    new_dna.calc_fitness()
    return new_dna

In [149]:
d1 = DNA()
print(d1.dvar)
d2 = DNA()
print(d2.dvar)

[0 0 1 1 0 0 0 0 0 1]
[0 0 0 1 0 1 1 1 1 0]


In [150]:
d3 = crossover(d1, d2)
print(d3.dvar)
print(d3.fitness)

[0 0 1 1 0 0 0 0 0 0]
3


In [151]:
d4 = DNA()
print(d4.dvar)


[0 1 0 1 1 1 0 1 1 0]


In [152]:
d4.mutate()
print(d4.dvar)

[0 0 0 1 1 1 0 1 1 0]


In [153]:
# initialize first population
pop_size = 20
population = []
for i in range(pop_size):
    population.append(DNA())
    population[i].calc_fitness()
    print(population[i].fitness)

-1
-15
-13
13
-4
7
-6
-12
3
8
-18
10
-4
-19
-5
1
15
9
1
4


In [154]:
pool = []
for i in range(pop_size):
    for j in range(floor(pow(2,max(population[i].fitness,0))/256)):
        pool.append(i)

print(pool)

[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 9, 11, 11, 11, 11, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 17, 17]


In [155]:
id1 = np.random.choice(pool)
id2 = np.random.choice(pool)
print(population[id1].dvar)
print(population[id2].dvar)

dna3 = crossover(population[id1], population[id2])
print(dna3.dvar)

[0 1 0 1 1 0 0 0 0 1]
[0 1 0 1 0 1 0 0 1 1]
[0 1 0 1 0 1 0 0 1 1]


In [156]:
num_of_iteration = 100
best_fit = -inf
best_dna = DNA()

for it in range(num_of_iteration):
    print("Generation", it)
    new_population = []
    pool = []
    for i in range(pop_size):
        for j in range(floor(pow(2,max(population[i].fitness,0))/256)):
            pool.append(i)
    for i in range(pop_size):
        id1 = np.random.choice(pool)
        id2 = np.random.choice(pool)
        dna3 = crossover(population[id1], population[id2])
        dna3.mutate()
        dna3.calc_fitness()
        if dna3.fitness > best_fit:
            best_fit = dna3.fitness
            best_dna = dna3
        new_population.append(dna3)
    population = new_population
    print("best =", best_fit)

Generation 0
best = 18
Generation 1
best = 24
Generation 2
best = 24
Generation 3
best = 24
Generation 4
best = 24
Generation 5
best = 24
Generation 6
best = 24
Generation 7
best = 25
Generation 8
best = 25
Generation 9
best = 25
Generation 10
best = 25
Generation 11
best = 25
Generation 12
best = 25
Generation 13
best = 25
Generation 14
best = 25
Generation 15
best = 25
Generation 16
best = 25
Generation 17
best = 25
Generation 18
best = 25
Generation 19
best = 25
Generation 20
best = 25
Generation 21
best = 25
Generation 22
best = 25
Generation 23
best = 25
Generation 24
best = 25
Generation 25
best = 25
Generation 26
best = 25
Generation 27
best = 25
Generation 28
best = 25
Generation 29
best = 25
Generation 30
best = 25
Generation 31
best = 25
Generation 32
best = 25
Generation 33
best = 25
Generation 34
best = 25
Generation 35
best = 25
Generation 36
best = 25
Generation 37
best = 25
Generation 38
best = 25
Generation 39
best = 25
Generation 40
best = 25
Generation 41
best = 25
Ge

In [158]:
print(best_dna.dvar)

[0 0 1 1 1 1 0 0 1 0]
